import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator:"Next.js",
  manifest:"/manifest.json",
  keywords:["nextjs","next15","pwa","next-pwa"],
  themeColor:[{media:"(preferers-color-schema:dark)",color:"#fff"}],
  authors:[
    {
      name:"iver",
      url:"http://github/Iver011"
    }
  ],
  
};

export const generateViewport = () => ({
  width: "device-width",
  initialScale: 1,
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Agregar manifest.json correctamente */}
        <link rel="manifest" href="/manifest.json" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="layout">
          <div className="container">{children}</div>
        </div>
      </body>
    </html>
  );
}
